### PR TITLE
Update DocumentWindow.cpp

### PR DESCRIPTION
**Pull request by Tiomat85**
Update DocumentWindow.cpp

Adding WheelEvent override to ComboBox to stop scrolling when not expanded.

### CODE REVIEW

**Comment by cmeyer** [comment]
Thanks I'll merge this after testing on my macOS. The macOS keychain stuff only works when building on the nion-software account, so these build failures are expected.

**Comment by cmeyer** [comment]
Why is this implementation different from the PyQtProxy implementation?

Also: the commit message "Update DocumentWindow.cpp" doesn't convey useful info.  I'll edit it to "Adding WheelEvent override to ComboBox to stop scrolling when not expanded." when merging.

**Comment by Tiomat85** [comment]
> Why is this implementation different from the PyQtProxy implementation?
The implementation is the same, if the combobox is expanded then we call back to the base combobox class with the event to handle it. If the combobox is collapsed, then we ignore the wheelevent coming in.  Which bits are you highlighting as different?


> Also: the commit message "Update DocumentWindow.cpp" doesn't convey useful info. I'll edit it to "Adding WheelEvent override to ComboBox to stop scrolling when not expanded." when merging.
This may have been messing up some squashing and reordering of commits. I had thought it was include the override of wheelevent bit but I may have lost that with a final squash. Thanks.

**Comment by cmeyer** [comment]
The change in PyQtProxy is here:
https://github.com/nion-software/nionui/pull/75/commits/d1641111034f3ad5562ab5731fbbeffe1063e335

It is only a single function change.

The change to DocumentWindow involves overriding show/hidePopUp and introduces an `expanded` bool variable.

The implementations look significantly different to me...

**Comment by Tiomat85** [comment]
Ah ok, so the python QT has the isVisible function for whether it is expanded or not, but from what I could see in the documentation for the C++ version there is no equivalent so I had to create one with the expanded variable bit. So starts expanded as false, and toggles when expanding/collapsing it.

**Comment by cmeyer** [comment]
`IsVisible` doesn't seem to be a public method - at least I can't find it documented anywhere. If it's not public, can you rewrite the PyQtProxy version to match the C++ version (and not use an undocumented API)?

**Comment by Tiomat85** [comment]
It is documented here:  https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QWidget.html#PySide2.QtWidgets.PySide2.QtWidgets.QWidget.isVisible
All widgets provide that to identify whether they are visible or not, and the call to view() pulls out the listbox that is the expanded part of it.

**Comment by cmeyer** [comment]
... minor note: we're using Qt6 not Qt5, but after searching I found https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QWidget.html#PySide6.QtWidgets.QWidget.isVisible

... additional note: search engines aren't that great, leading me down several incorrect paths when searching for "QWidget isVisible".

... C++ QWidget also has this function, so why not use the same code in the C++ version? https://doc.qt.io/qt-6/qwidget.html#visible-prop

**Comment by cmeyer** [comment]
Looks great! Merged here bfdb01bc78c8517fae832a9bbc2c2d72656ef224

**Pull request closed without merging**
